# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Build

on:
  push:
    branches: [ "main", "develop", "feature/*" ]
  workflow_dispatch:

jobs:
  build:
    uses:
      bigbird023/github-actions/.github/workflows/angular-build-workflow.yaml@main 
    with:
      TESTCOVERAGE_THRESHOLD: 0
      PULLREQUEST_FLAG: false

