# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Build Main

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        # node-version: [16.x, 18.x]
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3  
      with:
        fetch-depth: 0

    - name: Setup.NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.413'  

    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0
      with:
          versionSpec: '5.x'

    - name: Determine Version
      id: gitversion # step id used as reference for output values
      uses: gittools/actions/gitversion/execute@v0.9


    # uses:
    #   bigbird023/github-actions/.github/workflows/angular-build-workflow.yaml@main 
    # with:
    #   TESTCOVERAGE_THRESHOLD: 0

